repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.12.1
    hooks:
      - id: check-preference-manifests
        exclude: "^Resources/|^Manifests/ManagedPreferencesDeveloper/"
