repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    # Please use commit hash instead of tag
    rev: c668a2da8236a983ffaa0761fbbe31f90c0f5822
    hooks:
      - id: check-preference-manifests
        exclude: "^Resources/|^Manifests/ManagedPreferencesDeveloper/"
